/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Fatwa Linovera // A11.2019.11836
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double angka, jawaban;
    char simbol;
    public Calculator() {
        initComponents();
        radioON.setEnabled(false);
        textHasil.setEditable(false);
    }
    private void operasi_aritmatika(){
        switch(simbol){
            case '+':
                jawaban = angka+Double.parseDouble(textHasil.getText());
                textHasil.setText(Double.toString(jawaban));
                break;
            case '-':
                jawaban = angka-Double.parseDouble(textHasil.getText());
                textHasil.setText(Double.toString(jawaban));
                break;
            case '*':
                jawaban = angka*Double.parseDouble(textHasil.getText());
                textHasil.setText(Double.toString(jawaban));
                break;
            case '/':
                jawaban = angka/Double.parseDouble(textHasil.getText());
                textHasil.setText(Double.toString(jawaban));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        labelAtas = new javax.swing.JLabel();
        textHasil = new javax.swing.JTextField();
        radioON = new javax.swing.JRadioButton();
        radioOFF = new javax.swing.JRadioButton();
        tombol7 = new javax.swing.JButton();
        tombol0 = new javax.swing.JButton();
        tombol2 = new javax.swing.JButton();
        tombol8 = new javax.swing.JButton();
        tombol5 = new javax.swing.JButton();
        tombol9 = new javax.swing.JButton();
        tombol6 = new javax.swing.JButton();
        tombol3 = new javax.swing.JButton();
        tombolSamaDengan = new javax.swing.JButton();
        tombolKurang = new javax.swing.JButton();
        tombolKali = new javax.swing.JButton();
        tombolBagi = new javax.swing.JButton();
        tombolTitik = new javax.swing.JButton();
        tombol1 = new javax.swing.JButton();
        tombol4 = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolClear = new javax.swing.JButton();
        tombolTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        labelAtas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        textHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHasilActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioON);
        radioON.setText("ON");
        radioON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioONActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioOFF);
        radioOFF.setText("OFF");
        radioOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOFFActionPerformed(evt);
            }
        });

        tombol7.setText("7");
        tombol7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol7ActionPerformed(evt);
            }
        });

        tombol0.setText("0");
        tombol0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol0ActionPerformed(evt);
            }
        });

        tombol2.setText("2");
        tombol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol2ActionPerformed(evt);
            }
        });

        tombol8.setText("8");
        tombol8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol8ActionPerformed(evt);
            }
        });

        tombol5.setText("5");
        tombol5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol5ActionPerformed(evt);
            }
        });

        tombol9.setText("9");
        tombol9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol9ActionPerformed(evt);
            }
        });

        tombol6.setText("6");
        tombol6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol6ActionPerformed(evt);
            }
        });

        tombol3.setText("3");
        tombol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol3ActionPerformed(evt);
            }
        });

        tombolSamaDengan.setText("=");
        tombolSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSamaDenganActionPerformed(evt);
            }
        });

        tombolKurang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tombolKurang.setText("-");
        tombolKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKurangActionPerformed(evt);
            }
        });

        tombolKali.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tombolKali.setText("x");
        tombolKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKaliActionPerformed(evt);
            }
        });

        tombolBagi.setText("/");
        tombolBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBagiActionPerformed(evt);
            }
        });

        tombolTitik.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tombolTitik.setText(".");
        tombolTitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTitikActionPerformed(evt);
            }
        });

        tombol1.setText("1");
        tombol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol1ActionPerformed(evt);
            }
        });

        tombol4.setText("4");
        tombol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol4ActionPerformed(evt);
            }
        });

        tombolHapus.setText("<<");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        tombolClear.setText("C");
        tombolClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolClearActionPerformed(evt);
            }
        });

        tombolTambah.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tombolTambah.setText("+");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombol0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tombol6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tombol3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tombolKali, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tombolBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tombolSamaDengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tombol7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tombol8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(tombol9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tombolKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textHasil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioON)
                                        .addComponent(radioOFF))
                                    .addGap(18, 18, 18)
                                    .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(tombolClear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioOFF))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tombolClear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tombol8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tombol7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tombolKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombol5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombol4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombolKali, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombolBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombol6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombol3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioONActionPerformed
        tombol1.setEnabled(true);
        tombol2.setEnabled(true);
        tombol3.setEnabled(true);
        tombol4.setEnabled(true);
        tombol5.setEnabled(true);
        tombol6.setEnabled(true);
        tombol7.setEnabled(true);
        tombol8.setEnabled(true);
        tombol9.setEnabled(true);
        tombol0.setEnabled(true);
        tombolTambah.setEnabled(true);
        tombolKurang.setEnabled(true);
        tombolKali.setEnabled(true);
        tombolBagi.setEnabled(true);
        tombolTitik.setEnabled(true);
        tombolSamaDengan.setEnabled(true);
        tombolHapus.setEnabled(true);
        tombolClear.setEnabled(true);
        textHasil.setEnabled(true);
        radioOFF.setEnabled(true);
    }//GEN-LAST:event_radioONActionPerformed

    private void tombolKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKaliActionPerformed
        //textHasil.setText(textHasil.getText()+"x");
        angka = Double.parseDouble(textHasil.getText());
        simbol = '*';
        textHasil.setText("");
        labelAtas.setText(angka+"x");
    }//GEN-LAST:event_tombolKaliActionPerformed

    private void tombolClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolClearActionPerformed
        textHasil.setText("");
    }//GEN-LAST:event_tombolClearActionPerformed

    private void tombol7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol7ActionPerformed
        textHasil.setText(textHasil.getText()+"7");
    }//GEN-LAST:event_tombol7ActionPerformed

    private void tombol8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol8ActionPerformed
        textHasil.setText(textHasil.getText()+"8");

    }//GEN-LAST:event_tombol8ActionPerformed

    private void tombol9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol9ActionPerformed
        textHasil.setText(textHasil.getText()+"9");

    }//GEN-LAST:event_tombol9ActionPerformed

    private void tombol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol4ActionPerformed
        textHasil.setText(textHasil.getText()+"4");

    }//GEN-LAST:event_tombol4ActionPerformed

    private void tombol5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol5ActionPerformed
        textHasil.setText(textHasil.getText()+"5");
    }//GEN-LAST:event_tombol5ActionPerformed

    private void tombol6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol6ActionPerformed
        textHasil.setText(textHasil.getText()+"6");
    }//GEN-LAST:event_tombol6ActionPerformed

    private void tombol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol1ActionPerformed
        textHasil.setText(textHasil.getText()+"1");
    }//GEN-LAST:event_tombol1ActionPerformed

    private void tombol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol2ActionPerformed
        textHasil.setText(textHasil.getText()+"2");
    }//GEN-LAST:event_tombol2ActionPerformed

    private void tombol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol3ActionPerformed
        textHasil.setText(textHasil.getText()+"3");
    }//GEN-LAST:event_tombol3ActionPerformed

    private void tombol0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol0ActionPerformed
        textHasil.setText(textHasil.getText()+"0");
    }//GEN-LAST:event_tombol0ActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        //textHasil.setText(textHasil.getText()+"+");
        angka = Double.parseDouble(textHasil.getText());
        simbol = '+';
        textHasil.setText("");
        labelAtas.setText(angka+"+");
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tombolKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKurangActionPerformed
        //textHasil.setText(textHasil.getText()+"-");
        angka = Double.parseDouble(textHasil.getText());
        simbol = '-';
        textHasil.setText("");
        labelAtas.setText(angka+"-");
    }//GEN-LAST:event_tombolKurangActionPerformed

    private void tombolBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBagiActionPerformed
        //textHasil.setText(textHasil.getText()+"/");
        angka = Double.parseDouble(textHasil.getText());
        simbol = '/';
        textHasil.setText("");
        labelAtas.setText(angka+"/");
    }//GEN-LAST:event_tombolBagiActionPerformed

    private void radioOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOFFActionPerformed
        tombol1.setEnabled(false);
        tombol2.setEnabled(false);
        tombol3.setEnabled(false);
        tombol4.setEnabled(false);
        tombol5.setEnabled(false);
        tombol6.setEnabled(false);
        tombol7.setEnabled(false);
        tombol8.setEnabled(false);
        tombol9.setEnabled(false);
        tombol0.setEnabled(false);
        tombolTambah.setEnabled(false);
        tombolKurang.setEnabled(false);
        tombolKali.setEnabled(false);
        tombolBagi.setEnabled(false);
        tombolTitik.setEnabled(false);
        tombolSamaDengan.setEnabled(false);
        tombolHapus.setEnabled(false);
        tombolClear.setEnabled(false);
        textHasil.setEnabled(false);
        radioOFF.setEnabled(false);
        radioON.setEnabled(true);
    }//GEN-LAST:event_radioOFFActionPerformed

    private void tombolSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSamaDenganActionPerformed
        operasi_aritmatika();
        labelAtas.setText("");
    }//GEN-LAST:event_tombolSamaDenganActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        int length = textHasil.getText().length();
        int number = textHasil.getText().length()-1;
        String store;
        
        if (length>0) {
            StringBuilder back = new StringBuilder(textHasil.getText());
            back.deleteCharAt(number);
            store = back.toString();
            textHasil.setText(store);
        }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTitikActionPerformed
        if (textHasil.getText().toString().contains(".")) {
            textHasil.setText(textHasil.getText());
        }else{
            textHasil.setText(textHasil.getText()+".");
        }
    }//GEN-LAST:event_tombolTitikActionPerformed

    private void textHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel labelAtas;
    private javax.swing.JRadioButton radioOFF;
    private javax.swing.JRadioButton radioON;
    private javax.swing.JTextField textHasil;
    private javax.swing.JButton tombol0;
    private javax.swing.JButton tombol1;
    private javax.swing.JButton tombol2;
    private javax.swing.JButton tombol3;
    private javax.swing.JButton tombol4;
    private javax.swing.JButton tombol5;
    private javax.swing.JButton tombol6;
    private javax.swing.JButton tombol7;
    private javax.swing.JButton tombol8;
    private javax.swing.JButton tombol9;
    private javax.swing.JButton tombolBagi;
    private javax.swing.JButton tombolClear;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolKali;
    private javax.swing.JButton tombolKurang;
    private javax.swing.JButton tombolSamaDengan;
    private javax.swing.JButton tombolTambah;
    private javax.swing.JButton tombolTitik;
    // End of variables declaration//GEN-END:variables
}
